// <auto-generated />
using System;
using CarRentalApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalApi.Migrations
{
    [DbContext(typeof(CarRentalApiContext))]
    [Migration("20230517182834_NewTable")]
    partial class NewTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarRentalApi.Models.LastLoggedReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("LastLogged")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LastLoggings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastLogged = new DateTime(2023, 5, 14, 20, 18, 33, 876, DateTimeKind.Local).AddTicks(419),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            LastLogged = new DateTime(2023, 5, 15, 21, 28, 33, 876, DateTimeKind.Local).AddTicks(455),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            LastLogged = new DateTime(2023, 5, 16, 22, 38, 33, 876, DateTimeKind.Local).AddTicks(458),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            LastLogged = new DateTime(2023, 5, 17, 20, 28, 33, 876, DateTimeKind.Local).AddTicks(459),
                            UserId = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
