// <auto-generated />
using System;
using CarRentalApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalApi.Migrations
{
    [DbContext(typeof(CarRentalApiContext))]
    partial class CarRentalApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarRentalApi.Models.LastLoggedReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("LastLogged")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LastLoggings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastLogged = new DateTime(2023, 5, 8, 18, 35, 43, 307, DateTimeKind.Local).AddTicks(7399),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            LastLogged = new DateTime(2023, 5, 9, 19, 45, 43, 307, DateTimeKind.Local).AddTicks(7446),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            LastLogged = new DateTime(2023, 5, 10, 20, 55, 43, 307, DateTimeKind.Local).AddTicks(7449),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            LastLogged = new DateTime(2023, 5, 11, 18, 45, 43, 307, DateTimeKind.Local).AddTicks(7452),
                            UserId = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
